### PR TITLE
Fixed Bugs

### PR DESCRIPTION
**Pull request by rudranshg**
Responsive bugs on the homepage
Added hovering at few places
Adjusted some fonts
Added shadows at some places

new_site(1)
old_site(1)
responsive_Bug
responsive_bug_fixed
without_hover
with_hover(new)

### CODE REVIEW

**Review by mayant15 — COMMENTED** [review]
Great work! Not much feedback code wise. Can we maintain the aspect ratio for images when reducing page size?

**Comment by rudranshg** [comment]
I tried working on the aspect ratio and came up with this. The code I used is mentioned on the right. Thank You!

responsive_issue_sort

**Comment by mayant15** [comment]
@rudranshg Yes `object-fit` looks good. Commit to this same branch to update the PR, then we can merge 👍

**Comment by rudranshg** [comment]
Done

**Review by mayant15 — APPROVED** [review]

**Pull request merged**
